defaults:
  - _self_
  - data: \config\base
  - models: \config\base

cwd: G:\Shared drives\SI_NextGen_Aridity\dCFE\
save_name: debugger
output_dir: ${cwd}\output\
camels_attr_file: ${cwd}\data\camels_attributes_concat.csv
device: cpu
num_processes: 1


################## CHANGE HERE #######################
run_type: ML # Choose from: "generate_synthetic", "ML", "ML_synthetic", "ML_test"
# ML: training & validating ML against observed data
# ML_synthetic: training & validating ML against synthetic data
# generate_synthetic: generate synthetic data for ML_synthetic
# ML_test: testing ML
soil_scheme: classic # Choose from: "ode" or "classic"
######################################################

synthetic:
  output_dir: ${cwd}\data\synthetic_case\
  param_nams: ${basin_id}_synthetic_params_${soil_scheme}
  nams: synthetic_${soil_scheme}.csv
  Cgw: 1.0e-05
  satdk: 1.0e-04

test:
  input_dir: ${cwd}\output\2023-11-30_output_1430100
  epoch_to_use: 15

conversions:
  cm_to_mm: 10.0
  mm_to_cm: 0.1
  cm_to_m: 0.01
  m_to_mm: 1000
  hr_to_sec: 3600.0
  day_to_sec: 86400
  to_mega: 1000000
  to_kilo: 1000
  degC_to_K: 273.15

################## HYDRA CONFIG #######################
hydra:
  help:
    app_name: dCFE
    header: == ${hydra.help.app_name} ==
    template: |-
      ${hydra.help.header}

      This is ${hydra.help.app_name}!
      Work in progress

      ${hydra.help.footer}
    footer: |-
      Powered by Hydra (https:\\hydra.cc)
      Use --hydra-help to view Hydra specific help
  job:
    name: ${save_name}
  run:
    dir: ${cwd}\output\\${now:%Y-%m-%d}_${hydra.job.name} #\${now:%H-%M-%S}