hyperparameters:
  epochs: 2 #1000 #50
  learning_rate: 1 #0.1 # 0.001
  warmup: 2000
  step_size: 1
  gamma: 0.7

mlp:
  hidden_size: 6
  # input_size: 2
  num_attrs: 3
  # output_size: 2
  num_params: 2
  num_states: 2

transformation:
  Cgw: 
  - 1.8e-6
  - 1.8e-3
  satdk:
  - 0
  - 7.26e-04

initial_params:
  Cgw: 3
  satdk: 1.0e-03
