hyperparameters:
  epochs: 5 #1000 #50
  learning_rate: 1.0e-2 #0.1 # 0.001
  warmup: 2000
  step_size: 1
  gamma: 0.92

mlp:
  hidden_size: 256
  num_attrs: 3
  num_params: 2
  num_states: 2
  lag_hrs: 24

transformation:
  Cgw: 
  - 1.8e-6
  - 1.8e-3
  satdk:
  - 0
  - 7.26e-04

initial_params:
  Cgw: 2.55e-04
  satdk: 1.82e-02
